<?xml version="1.0" encoding="utf-8"?>
      <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html;charset=utf-8" ></meta>
        <meta http-equiv="Expires" content="0" />
        <title>org/scalatest/FailureOf.scala</title>
        <script type="text/javascript" src="../../jquery-all.js"></script>
        <script type="text/javascript" src="../../linked.js"></script>
        <link rel="stylesheet" type="text/css" href="../../style.css" title="Style"></link>
    </head>
    <body>
        <pre>
<span class="comment">/*
 * Copyright 2001-2008 Artima, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an &quot;AS IS&quot; BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */</span>
<span class="keyword">package</span> org.scalatest

<span class="comment">/**
 * Trait that contains the &lt;code&gt;failureOf&lt;/code&gt; method, which captures an exception thrown by a passed code block and
 * returns it wrapped in a &lt;code&gt;Some&lt;/code&gt;, or returns &lt;code&gt;None&lt;/code&gt; if no exception is thrown.
 *
 * @author Bill Venners
 */</span>
<span class="keyword">trait</span> <a title="trait FailureOf extends java.lang.Object with ScalaObject" id="10184">FailureOf</a> <span title="ScalaObject" class="delimiter">{</span>

  <span class="comment">/**
   * Executes the supplied code (a by-name parameter) and returns in an optional throwable indicating whether the passed
   * expression failed (threw an exception that would normally cause a test to fail) or succeeded (did not throw any exception).
   *
   * &lt;p&gt;
   * Because &lt;code&gt;Error&lt;/code&gt;s are used to denote serious errors, trait &lt;code&gt;Suite&lt;/code&gt; and its subtypes in the
   * ScalaTest API do not always treat a test that completes abruptly with an &lt;code&gt;Error&lt;/code&gt; as a test failure, but sometimes as
   * an indication that serious problems have arisen that should cause the run to abort. For example, if a test completes abruptly
   * with an &lt;code&gt;OutOfMemoryError&lt;/code&gt;, it will not be reported as a test failure, but will instead cause the run to abort.
   * Because not everyone uses &lt;code&gt;Error&lt;/code&gt;s only to represent serious problems, however, ScalaTest only behaves this way
   * for the following exception types (and their subclasses):
   * &lt;/p&gt;
   *
   * &lt;ul&gt;
   * &lt;li&gt;&lt;code&gt;java.lang.annotation.AnnotationFormatError&lt;/code&gt;&lt;/li&gt;
   * &lt;li&gt;&lt;code&gt;java.awt.AWTError&lt;/code&gt;&lt;/li&gt;
   * &lt;li&gt;&lt;code&gt;java.nio.charset.CoderMalfunctionError&lt;/code&gt;&lt;/li&gt;
   * &lt;li&gt;&lt;code&gt;javax.xml.parsers.FactoryConfigurationError&lt;/code&gt;&lt;/li&gt;
   * &lt;li&gt;&lt;code&gt;java.lang.LinkageError&lt;/code&gt;&lt;/li&gt;
   * &lt;li&gt;&lt;code&gt;java.lang.ThreadDeath&lt;/code&gt;&lt;/li&gt;
   * &lt;li&gt;&lt;code&gt;javax.xml.transform.TransformerFactoryConfigurationError&lt;/code&gt;&lt;/li&gt;
   * &lt;li&gt;&lt;code&gt;java.lang.VirtualMachineError&lt;/code&gt;&lt;/li&gt;
   * &lt;/ul&gt;
   *
   * &lt;p&gt;
   * The previous list includes all &lt;code&gt;Error&lt;/code&gt;s that exist as part of Java 1.5 API, excluding &lt;code&gt;java.lang.AssertionError&lt;/code&gt;. ScalaTest
   * does treat a thrown &lt;code&gt;AssertionError&lt;/code&gt; as an indication of a test failure. In addition, any other &lt;code&gt;Error&lt;/code&gt; that is not an instance of a
   * type mentioned in the previous list will be caught by the &lt;code&gt;Suite&lt;/code&gt; traits in the ScalaTest API and reported as the cause of a test failure. 
   * &lt;/p&gt;
   *
   * &lt;p&gt;
   * If the code supplied to &lt;code&gt;failureOf&lt;/code&gt; completes abruptly in one of the errors in the previous list, &lt;code&gt;failureOf&lt;/code&gt;
   * will not return it wrapped in an option, but rather will complete abruptly with the same exception. The &lt;code&gt;failureOf&lt;/code&gt; method
   * will wrap any other exception thrown by the supplied code in a &lt;code&gt;Some&lt;/code&gt; and return it.
   * &lt;/p&gt;
   */</span>
  <span class="keyword">def</span> <a title="(f: =&gt; Unit)Option[Throwable]" id="41989">failureOf</a><span class="delimiter">(</span><a title="=&gt; Unit" id="41992">f</a>: =&gt; Unit<span class="delimiter">)</span>: <span title="Option[Throwable]">Option</span><span class="delimiter">[</span>Throwable<span class="delimiter">]</span> = <span class="delimiter">{</span>
    
    <span class="keyword">try</span> <span class="delimiter">{</span>                                         
      <a href="#41992" title="=&gt; Unit">f</a>                                           
      <span title="object None">None</span>                                        
    <span class="delimiter">}</span>                                             
    <span class="keyword">catch</span> <span class="delimiter">{</span>                                       
      <span class="keyword">case</span> <a title="Option[Throwable]" id="41994">e</a> =&gt;
        <span title="Option[Throwable]" class="keyword">if</span> <span class="delimiter">(</span><span title="=&gt; Boolean">!</span><a href="Suite.scala.html#10074" title="object org.scalatest.Suite">Suite</a>.<a href="Suite.scala.html#27211" title="(throwable: Throwable)Boolean">anErrorThatShouldCauseAnAbort</a><span class="delimiter">(</span><a href="#41994" title="java.lang.Throwable">e</a><span class="delimiter">)</span><span class="delimiter">)</span>
          <span title="(x: java.lang.Throwable)Some[java.lang.Throwable]">Some</span><span class="delimiter">(</span><a href="#41994" title="java.lang.Throwable">e</a><span class="delimiter">)</span>                           
        <span class="keyword">else</span>
          <span title="Nothing" class="keyword">throw</span> <a href="#41994" title="java.lang.Throwable">e</a>
    <span class="delimiter">}</span>
  <span class="delimiter">}</span>
<span class="delimiter">}</span>

<span class="comment">/**
 * Companion object that facilitates the importing of &lt;code&gt;FailureOf&lt;/code&gt;'s method as 
 * an alternative to mixing it in. One use case is to import &lt;code&gt;FailureOf&lt;/code&gt;'s method so you can use
 * it in the Scala interpreter:
 *
 * &lt;pre class=&quot;stREPL&quot;&gt;
 * $scala -classpath scalatest.jar
 * Welcome to Scala version 2.8.0.final (Java HotSpot(TM) 64-Bit Server VM, Java 1.6.0_22).
 * Type in expressions to have them evaluated.
 * Type :help for more information.
 * &amp;nbsp;
 * scala&gt; import org.scalatest.Assertions._
 * import org.scalatest.Assertions._
 * &amp;nbsp;
 * scala&gt; import org.scalatest.FailureOf._
 * import org.scalatest.FailureOf._
 * &amp;nbsp;
 * scala&gt; failureOf { assert(1 + 1 === 2) }
 * res0: Option[Throwable] = None
 * &amp;nbsp;
 * scala&gt; failureOf { assert(1 + 1 === 3) }
 * res1: Option[Throwable] = Some(org.scalatest.TestFailedException: 2 did not equal 3)
 * &lt;pre&gt;
 *
 * @author Bill Venners
 */</span>
<span class="keyword">object</span> <a title="object org.scalatest.FailureOf" id="10185">FailureOf</a> <span title="ScalaObject" class="keyword">extends</span> <a href="#10184" title="org.scalatest.FailureOf">FailureOf</a>

        </pre>
    </body>
</html>